import {
  Globe,
  LogIn,
  UserPlus,
  LayoutDashboard,
  CreditCard,
  Settings,
  Database,
  Table2,
  Lock,
  Zap,
  Sparkles,
  Mail,
  ShieldCheck,
  DollarSign,
} from 'lucide-react'
import { hasBackend } from '@/lib/api'
import type { WorkspaceGraph } from '../types'

// BACKEND: replace mock branch with apiGet<WorkspaceGraph>(`/startups/${startupId}/workspace`)
// Note: API returns iconName (string); resolve to LucideIcon client-side via a nodeType→icon map
// before returning, since WorkspaceAsset.icon is an ElementType (not JSON-serializable).
export async function getWorkspaceGraph(startupId: string): Promise<WorkspaceGraph> {
  if (hasBackend) throw new Error('getWorkspaceGraph: real API not yet implemented — set up icon resolution first')
  return {
    startupId,
    startupName: formatStartupName(startupId),
    generatedAt: new Date().toISOString(),

    assets: [
      // ── Pages ──────────────────────────────────────────────────────────────

      {
        id: 'landing',
        nodeType: 'page',
        assetType: 'marketing',
        status: 'generated',
        title: 'Landing Page',
        description: 'Public-facing marketing page',
        route: '/',
        x: 80,
        y: 180,
        w: 200,
        h: 148,
        revealDelay: 0,
        purpose: 'First impression for potential users. Communicates the product value proposition and drives signups.',
        impact: 'Removing this breaks the primary acquisition channel.',
        aiRecommendation: 'Add a live demo section. Startups with interactive previews see 2× higher signup conversion.',
        dependencies: [],
        icon: Globe,
      },
      {
        id: 'signup',
        nodeType: 'page',
        assetType: 'auth',
        status: 'generated',
        title: 'Signup',
        description: 'New user registration flow',
        route: '/signup',
        x: 80,
        y: 384,
        w: 200,
        h: 148,
        revealDelay: 1,
        purpose: 'Converts visitors into users. Collects credentials and triggers onboarding.',
        impact: 'Removing this stops all new user acquisition.',
        aiRecommendation: 'Add Google OAuth. Single-click signup improves completion rate by ~35%.',
        dependencies: ['auth-service'],
        icon: UserPlus,
      },
      {
        id: 'login',
        nodeType: 'page',
        assetType: 'auth',
        status: 'generated',
        title: 'Login',
        description: 'Returning user authentication',
        route: '/login',
        x: 80,
        y: 588,
        w: 200,
        h: 148,
        revealDelay: 2,
        purpose: 'Re-authenticates existing users and restores their session.',
        impact: 'Removing this locks all existing users out of the product.',
        aiRecommendation: 'Add magic link login as a fallback. Reduces password-reset support by 60%.',
        dependencies: ['auth-service'],
        icon: LogIn,
      },
      {
        id: 'dashboard',
        nodeType: 'page',
        assetType: 'core',
        status: 'generated',
        title: 'Dashboard',
        description: 'Primary workspace for authenticated users',
        route: '/app/dashboard',
        x: 380,
        y: 310,
        w: 230,
        h: 168,
        revealDelay: 3,
        isHub: true,
        purpose: 'Central hub. Every authenticated user lands here. Surfaces key metrics, recent activity, and navigation.',
        impact: 'Removing this collapses the entire post-login experience.',
        aiRecommendation: 'Add an empty-state checklist for new users. Guided activation increases 7-day retention by 40%.',
        dependencies: ['auth-service', 'users-table', 'billing-service'],
        icon: LayoutDashboard,
      },
      {
        id: 'pricing',
        nodeType: 'page',
        assetType: 'billing',
        status: 'generated',
        title: 'Pricing',
        description: 'Plan comparison and upgrade flow',
        route: '/pricing',
        x: 380,
        y: 100,
        w: 200,
        h: 148,
        revealDelay: 4,
        purpose: 'Drives upgrade intent. Shows plan tiers and routes users to checkout.',
        impact: 'Removing this cuts the primary paid conversion path.',
        aiRecommendation: 'Show a "Most Popular" badge on the recommended tier. Reduces decision fatigue and lifts conversion.',
        dependencies: ['billing-service', 'stripe-integration'],
        icon: CreditCard,
      },
      {
        id: 'settings',
        nodeType: 'page',
        assetType: 'settings',
        status: 'generated',
        title: 'Settings',
        description: 'Account and workspace configuration',
        route: '/app/settings',
        x: 380,
        y: 540,
        w: 200,
        h: 148,
        revealDelay: 5,
        purpose: 'Lets users manage profile, notification preferences, billing, and integrations.',
        impact: 'Removing this forces users to contact support for any configuration change.',
        aiRecommendation: 'Surface an integrations marketplace here. Integration-connected users have 3× lower churn.',
        dependencies: ['auth-service', 'billing-service'],
        icon: Settings,
      },

      // ── Database ───────────────────────────────────────────────────────────

      {
        id: 'users-table',
        nodeType: 'database',
        assetType: 'table',
        status: 'generated',
        title: 'Users',
        description: 'Core user identity and profile records',
        x: 720,
        y: 100,
        w: 190,
        h: 140,
        revealDelay: 6,
        purpose: 'Source of truth for all user identity data — credentials, profile, roles.',
        impact: 'This is the root table. Removing it cascades failures across auth, billing, and all user-scoped data.',
        aiRecommendation: 'Add a `last_active_at` column now. You will need it for churn prediction and nudge workflows.',
        dependencies: [],
        icon: Database,
      },
      {
        id: 'subscriptions-table',
        nodeType: 'database',
        assetType: 'table',
        status: 'generated',
        title: 'Subscriptions',
        description: 'Plan, billing cycle, and payment state',
        x: 720,
        y: 296,
        w: 190,
        h: 140,
        revealDelay: 7,
        purpose: 'Tracks each user\'s active plan, renewal dates, and payment status.',
        impact: 'Without this, billing logic has no state to read from and all gating breaks.',
        aiRecommendation: 'Add a `trial_ends_at` column. Trial-aware UI improves trial-to-paid conversion by ~22%.',
        dependencies: ['users-table'],
        icon: Table2,
      },
      {
        id: 'sessions-table',
        nodeType: 'database',
        assetType: 'table',
        status: 'generated',
        title: 'Sessions',
        description: 'Active auth session tokens',
        x: 720,
        y: 492,
        w: 190,
        h: 140,
        revealDelay: 8,
        purpose: 'Stores active auth tokens. Enables secure session validation and revocation.',
        impact: 'Without this, the Auth Service cannot validate or revoke user sessions.',
        dependencies: ['users-table'],
        icon: Lock,
      },

      // ── Integrations ───────────────────────────────────────────────────────

      {
        id: 'stripe-integration',
        nodeType: 'integration',
        assetType: 'payment',
        status: 'needs-config',
        title: 'Stripe',
        description: 'Payment processing and subscription billing',
        x: 1020,
        y: 180,
        w: 200,
        h: 148,
        revealDelay: 9,
        purpose: 'Processes payments, manages subscriptions, and handles webhooks for billing events.',
        impact: 'Without Stripe, the entire monetization layer is non-functional.',
        aiRecommendation: 'Connect your Stripe API key to activate billing. Add the webhook endpoint to complete the payment loop.',
        dependencies: [],
        icon: CreditCard,
      },
      {
        id: 'resend-integration',
        nodeType: 'integration',
        assetType: 'email',
        status: 'needs-config',
        title: 'Resend',
        description: 'Transactional and lifecycle email delivery',
        x: 1020,
        y: 384,
        w: 200,
        h: 148,
        revealDelay: 10,
        purpose: 'Delivers transactional emails (verification, receipts) and lifecycle nudges.',
        impact: 'Without Resend, email verification breaks and all automated lifecycle emails stop.',
        aiRecommendation: 'Set up a verified sending domain before launch. Branded emails see 4× higher open rates than shared domains.',
        dependencies: [],
        icon: Mail,
      },

      // ── System ─────────────────────────────────────────────────────────────

      {
        id: 'auth-service',
        nodeType: 'system',
        assetType: 'service',
        status: 'generated',
        title: 'Auth Service',
        description: 'JWT issuance, OAuth2, and session management',
        x: 720,
        y: 688,
        w: 200,
        h: 148,
        revealDelay: 11,
        purpose: 'Issues and validates JWTs. Handles OAuth2 provider callbacks. Manages session lifecycle.',
        impact: 'Central auth dependency. Removing this breaks all authenticated routes.',
        aiRecommendation: 'Implement refresh token rotation now. It prevents session hijacking without hurting UX.',
        dependencies: ['users-table', 'sessions-table'],
        icon: ShieldCheck,
      },
      {
        id: 'billing-service',
        nodeType: 'system',
        assetType: 'service',
        status: 'needs-config',
        title: 'Billing Service',
        description: 'Plan gating, subscription lifecycle, and invoicing',
        x: 1020,
        y: 580,
        w: 200,
        h: 148,
        revealDelay: 12,
        purpose: 'Enforces plan limits, processes upgrades/downgrades, and syncs billing state with Stripe.',
        impact: 'Without this, all plan gating fails and users get unlimited access regardless of tier.',
        aiRecommendation: 'Add a usage-based metering hook here for future seat-based pricing. Much easier to retrofit now.',
        dependencies: ['subscriptions-table', 'stripe-integration'],
        icon: DollarSign,
      },

      // ── Workflows ──────────────────────────────────────────────────────────

      {
        id: 'onboarding-workflow',
        nodeType: 'workflow',
        assetType: 'automation',
        status: 'generated',
        title: 'Onboarding',
        description: 'Post-signup activation sequence',
        x: 1340,
        y: 180,
        w: 210,
        h: 148,
        revealDelay: 13,
        purpose: 'Fires after signup. Sends welcome email, creates default workspace, and seeds initial data.',
        impact: 'Without this, new users land in an empty product with no guidance.',
        aiRecommendation: 'Add a day-3 check-in step. Users who receive a day-3 nudge complete setup at 2× the rate.',
        dependencies: ['resend-integration', 'users-table'],
        icon: Sparkles,
      },
      {
        id: 'payment-workflow',
        nodeType: 'workflow',
        assetType: 'trigger',
        status: 'needs-config',
        title: 'Payment',
        description: 'Subscription created, updated, and failed events',
        x: 1340,
        y: 384,
        w: 210,
        h: 148,
        revealDelay: 14,
        purpose: 'Handles Stripe webhook events — activates plans on payment, downgrades on failure, sends receipts.',
        impact: 'Without this, successful payments do not activate plans and failed payments are silently ignored.',
        aiRecommendation: 'Add a payment-failed retry sequence with 3 attempts over 7 days before canceling.',
        dependencies: ['stripe-integration', 'billing-service', 'resend-integration'],
        icon: Zap,
      },
      {
        id: 'nudge-workflow',
        nodeType: 'workflow',
        assetType: 'scheduled',
        status: 'planned',
        title: 'Nudge Emails',
        description: 'Day-7 and day-14 re-engagement emails',
        x: 1340,
        y: 588,
        w: 210,
        h: 148,
        revealDelay: 15,
        purpose: 'Re-engages users who have not returned after signup. Sends personalized nudges at day 7 and day 14.',
        impact: 'Skipping this loses ~30% of users who would have reactivated with a single email.',
        aiRecommendation: 'Personalize the day-7 nudge with the user\'s last action. Behavior-triggered emails outperform generic ones by 6×.',
        dependencies: ['resend-integration', 'users-table'],
        icon: Mail,
      },
    ],

    connectors: [
      // Entry → Auth pages
      { id: 'c-land-signup', from: 'landing', to: 'signup', relationshipType: 'navigates-to', fromSide: 'bottom', toSide: 'top', animated: true },
      { id: 'c-land-login', from: 'landing', to: 'login', relationshipType: 'navigates-to', fromSide: 'bottom', toSide: 'top', animated: true },

      // Auth pages → Auth Service
      { id: 'c-signup-auth', from: 'signup', to: 'auth-service', relationshipType: 'authenticates', fromSide: 'right', toSide: 'left' },
      { id: 'c-login-auth', from: 'login', to: 'auth-service', relationshipType: 'authenticates', fromSide: 'right', toSide: 'left' },

      // Auth pages → Dashboard
      { id: 'c-signup-dash', from: 'signup', to: 'dashboard', relationshipType: 'navigates-to', fromSide: 'right', toSide: 'left', animated: true },
      { id: 'c-login-dash', from: 'login', to: 'dashboard', relationshipType: 'navigates-to', fromSide: 'right', toSide: 'left', animated: true },

      // Dashboard → Feature pages
      { id: 'c-dash-pricing', from: 'dashboard', to: 'pricing', relationshipType: 'navigates-to', fromSide: 'top', toSide: 'bottom', animated: true },
      { id: 'c-dash-settings', from: 'dashboard', to: 'settings', relationshipType: 'navigates-to', fromSide: 'bottom', toSide: 'top', animated: true },

      // Auth Service → DB
      { id: 'c-auth-users', from: 'auth-service', to: 'users-table', relationshipType: 'reads', fromSide: 'top', toSide: 'bottom' },
      { id: 'c-auth-sessions', from: 'auth-service', to: 'sessions-table', relationshipType: 'writes', fromSide: 'right', toSide: 'left' },

      // Billing Service → DB + Integration
      { id: 'c-billing-subs', from: 'billing-service', to: 'subscriptions-table', relationshipType: 'writes', fromSide: 'left', toSide: 'right' },
      { id: 'c-billing-stripe', from: 'billing-service', to: 'stripe-integration', relationshipType: 'calls', fromSide: 'top', toSide: 'bottom' },

      // Dashboard → Services
      { id: 'c-dash-billing', from: 'dashboard', to: 'billing-service', relationshipType: 'uses', fromSide: 'right', toSide: 'left' },

      // Signup → Onboarding Workflow
      { id: 'c-signup-onboard', from: 'signup', to: 'onboarding-workflow', relationshipType: 'triggers', fromSide: 'right', toSide: 'left', animated: true },

      // Onboarding Workflow → Resend
      { id: 'c-onboard-resend', from: 'onboarding-workflow', to: 'resend-integration', relationshipType: 'sends', fromSide: 'bottom', toSide: 'top' },

      // Payment Workflow → Services
      { id: 'c-pay-stripe', from: 'payment-workflow', to: 'stripe-integration', relationshipType: 'calls', fromSide: 'bottom', toSide: 'top' },
      { id: 'c-pay-billing', from: 'payment-workflow', to: 'billing-service', relationshipType: 'uses', fromSide: 'bottom', toSide: 'top' },
      { id: 'c-pay-resend', from: 'payment-workflow', to: 'resend-integration', relationshipType: 'sends', fromSide: 'left', toSide: 'right' },

      // Nudge Workflow → Resend
      { id: 'c-nudge-resend', from: 'nudge-workflow', to: 'resend-integration', relationshipType: 'sends', fromSide: 'left', toSide: 'right' },
    ],
  }
}

function formatStartupName(id: string): string {
  return id
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}
