'use client'

import { motion } from 'framer-motion'
import { cn } from '@/lib/utils'
import { ProgressRing } from '../ui/progress-ring'
import { METRICS, BLUEPRINT_HEALTH_SCORE } from '../constants'

export function MetricsSidebar() {
  return (
    <aside className="relative">
      <div className="sticky top-[73px] h-fit space-y-5">
        <div className="bg-white/[0.03] border border-white/[0.06] rounded-xl p-5">
          <p className="text-[10px] font-semibold tracking-[0.18em] text-zinc-600 uppercase mb-5 text-center">
            Blueprint Health
          </p>
          <ProgressRing percentage={BLUEPRINT_HEALTH_SCORE} />
          <p className="text-center text-[10px] font-medium text-zinc-700 mt-3 uppercase tracking-widest">
            Overall Score
          </p>
        </div>

        <div className="space-y-4 px-1">
          {METRICS.map((metric, i) => (
            <div key={metric.label}>
              <div className="flex justify-between text-[11px] font-medium mb-1.5">
                <span className="text-zinc-500">{metric.label}</span>
                <span className="text-zinc-300">{metric.val}%</span>
              </div>
              <div className="h-[3px] w-full bg-white/[0.05] rounded-full overflow-hidden">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${metric.val}%` }}
                  transition={{ duration: 1, delay: 0.3 + i * 0.1 }}
                  className={cn('h-full rounded-full', metric.color)}
                />
              </div>
            </div>
          ))}
        </div>

        <p className="text-[10px] text-zinc-700 text-center uppercase tracking-widest">
          Blueprint generated by Xenysis AI · Just now
        </p>
      </div>
    </aside>
  )
}
