import type { DesignProfile, StartupCategory, VisualStyle } from '../types'

const CATEGORY_TO_STYLE: Record<StartupCategory, VisualStyle> = {
  saas:              'modern-saas',
  healthcare:        'healthcare',
  fintech:           'fintech',
  marketplace:       'marketplace',
  ecommerce:         'marketplace',
  'developer-tool':  'developer-tool',
  'ai-tool':         'ai-product',
  social:            'creator',
}

// ── Profile definitions ────────────────────────────────────────────────────────

const PROFILES: Record<VisualStyle, DesignProfile> = {

  // ── Modern SaaS — light, blue, spacious ──────────────────────────────────────
  'modern-saas': {
    visualStyle: 'modern-saas',
    colorMode: 'light',
    primary:       '#2563EB',
    primaryFg:     '#FFFFFF',
    primarySubtle: 'rgba(37,99,235,0.08)',
    primaryBorder: 'rgba(37,99,235,0.18)',
    background:    '#F8FAFC',
    surface:       '#FFFFFF',
    surfaceHover:  '#F1F5F9',
    border:        '#E2E8F0',
    borderStrong:  '#CBD5E1',
    text:          '#0F172A',
    textMuted:     '#475569',
    textFaint:     '#94A3B8',
    fontFamily:    '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyMono:'"Fira Code", "Cascadia Code", monospace',
    fontWeightBold: 700,
    radius:        8,
    radiusSm:      4,
    radiusLg:      12,
    radiusFull:    999,
    density:       'spacious',
    shadow:        '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
    glowPrimary:   '0 0 0 2px rgba(37,99,235,0.18)',
    navPattern:    'sidebar-icon',
    success:       '#10B981',
    warning:       '#F59E0B',
    danger:        '#EF4444',
  },

  // ── Healthcare — light, medical blue, trust-first, spacious ──────────────────
  'healthcare': {
    visualStyle:   'healthcare',
    colorMode:     'light',
    primary:       '#0284C7',
    primaryFg:     '#FFFFFF',
    primarySubtle: 'rgba(2,132,199,0.08)',
    primaryBorder: 'rgba(2,132,199,0.2)',
    background:    '#F0F9FF',
    surface:       '#FFFFFF',
    surfaceHover:  '#E0F2FE',
    border:        '#BAE6FD',
    borderStrong:  '#7DD3FC',
    text:          '#0C4A6E',
    textMuted:     '#0369A1',
    textFaint:     '#38BDF8',
    fontFamily:    '"Inter", -apple-system, "Helvetica Neue", sans-serif',
    fontFamilyMono:'"Fira Code", monospace',
    fontWeightBold: 600,
    radius:        6,
    radiusSm:      4,
    radiusLg:      8,
    radiusFull:    999,
    density:       'spacious',
    shadow:        '0 1px 4px rgba(2,132,199,0.08), 0 1px 2px rgba(0,0,0,0.04)',
    glowPrimary:   '0 0 0 2px rgba(2,132,199,0.2)',
    navPattern:    'sidebar-full',
    success:       '#059669',
    warning:       '#D97706',
    danger:        '#DC2626',
  },

  // ── Fintech — dark navy, sharp edges, dense data ─────────────────────────────
  'fintech': {
    visualStyle:   'fintech',
    colorMode:     'dark',
    primary:       '#3B82F6',
    primaryFg:     '#FFFFFF',
    primarySubtle: 'rgba(59,130,246,0.1)',
    primaryBorder: 'rgba(59,130,246,0.25)',
    background:    '#060B18',
    surface:       '#0D1526',
    surfaceHover:  '#162035',
    border:        'rgba(51,65,85,0.8)',
    borderStrong:  'rgba(71,85,105,1)',
    text:          '#F1F5F9',
    textMuted:     '#94A3B8',
    textFaint:     '#475569',
    fontFamily:    '"IBM Plex Sans", "Inter", sans-serif',
    fontFamilyMono:'"IBM Plex Mono", "Fira Code", monospace',
    fontWeightBold: 700,
    radius:        4,
    radiusSm:      2,
    radiusLg:      6,
    radiusFull:    4,
    density:       'compact',
    shadow:        '0 4px 24px rgba(0,0,0,0.5)',
    glowPrimary:   '0 0 20px rgba(59,130,246,0.15)',
    navPattern:    'sidebar-icon',
    success:       '#10B981',
    warning:       '#F59E0B',
    danger:        '#EF4444',
  },

  // ── Creator — dark, bold, gradient purple/pink ────────────────────────────────
  'creator': {
    visualStyle:      'creator',
    colorMode:        'dark',
    primary:          '#A855F7',
    primaryFg:        '#FFFFFF',
    primaryGradient:  'linear-gradient(135deg, #A855F7 0%, #EC4899 100%)',
    primarySubtle:    'rgba(168,85,247,0.1)',
    primaryBorder:    'rgba(168,85,247,0.25)',
    background:       '#09090B',
    surface:          '#18181B',
    surfaceHover:     '#27272A',
    border:           'rgba(255,255,255,0.07)',
    borderStrong:     'rgba(255,255,255,0.15)',
    text:             '#FAFAFA',
    textMuted:        '#A1A1AA',
    textFaint:        '#52525B',
    fontFamily:       '"Inter", -apple-system, sans-serif',
    fontFamilyMono:   'monospace',
    fontWeightBold:   800,
    radius:           16,
    radiusSm:         8,
    radiusLg:         20,
    radiusFull:       999,
    density:          'normal',
    shadow:           '0 8px 40px rgba(0,0,0,0.6)',
    glowPrimary:      '0 0 30px rgba(168,85,247,0.35)',
    navPattern:       'topnav',
    success:          '#4ADE80',
    warning:          '#FBBF24',
    danger:           '#EF4444',
  },

  // ── Marketplace — light, orange/amber, commercial ─────────────────────────────
  'marketplace': {
    visualStyle:   'marketplace',
    colorMode:     'light',
    primary:       '#EA580C',
    primaryFg:     '#FFFFFF',
    primarySubtle: 'rgba(234,88,12,0.08)',
    primaryBorder: 'rgba(234,88,12,0.2)',
    background:    '#FFFFFF',
    surface:       '#FFFFFF',
    surfaceHover:  '#FFF7ED',
    border:        '#E7E5E4',
    borderStrong:  '#A8A29E',
    text:          '#1C1917',
    textMuted:     '#78716C',
    textFaint:     '#A8A29E',
    fontFamily:    '-apple-system, "Helvetica Neue", "Arial", sans-serif',
    fontFamilyMono:'"Fira Code", monospace',
    fontWeightBold: 700,
    radius:        8,
    radiusSm:      4,
    radiusLg:      12,
    radiusFull:    999,
    density:       'normal',
    shadow:        '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
    glowPrimary:   '0 0 0 2px rgba(234,88,12,0.2)',
    navPattern:    'topnav',
    success:       '#16A34A',
    warning:       '#D97706',
    danger:        '#DC2626',
  },

  // ── Developer Tool — dark terminal, green, monospace ─────────────────────────
  'developer-tool': {
    visualStyle:   'developer-tool',
    colorMode:     'dark',
    primary:       '#22C55E',
    primaryFg:     '#000000',
    primarySubtle: 'rgba(34,197,94,0.08)',
    primaryBorder: 'rgba(34,197,94,0.2)',
    background:    '#0C0C0C',
    surface:       '#141414',
    surfaceHover:  '#1C1C1C',
    border:        'rgba(255,255,255,0.07)',
    borderStrong:  'rgba(255,255,255,0.14)',
    text:          '#E4E4E7',
    textMuted:     '#71717A',
    textFaint:     '#3F3F46',
    fontFamily:    '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
    fontFamilyMono:'"JetBrains Mono", "Fira Code", monospace',
    fontWeightBold: 700,
    radius:        4,
    radiusSm:      2,
    radiusLg:      4,
    radiusFull:    4,
    density:       'compact',
    shadow:        'none',
    glowPrimary:   '0 0 12px rgba(34,197,94,0.3)',
    navPattern:    'sidebar-icon',
    success:       '#22C55E',
    warning:       '#EAB308',
    danger:        '#EF4444',
  },

  // ── AI Product — dark violet, elegant, gradient accents ──────────────────────
  'ai-product': {
    visualStyle:      'ai-product',
    colorMode:        'dark',
    primary:          '#8B5CF6',
    primaryFg:        '#FFFFFF',
    primaryGradient:  'linear-gradient(135deg, #8B5CF6 0%, #6366F1 100%)',
    primarySubtle:    'rgba(139,92,246,0.1)',
    primaryBorder:    'rgba(139,92,246,0.2)',
    background:       '#030712',
    surface:          '#0F172A',
    surfaceHover:     '#1E293B',
    border:           'rgba(139,92,246,0.15)',
    borderStrong:     'rgba(139,92,246,0.3)',
    text:             '#F9FAFB',
    textMuted:        '#9CA3AF',
    textFaint:        '#4B5563',
    fontFamily:       '"Inter", -apple-system, sans-serif',
    fontFamilyMono:   '"Fira Code", monospace',
    fontWeightBold:   700,
    radius:           10,
    radiusSm:         6,
    radiusLg:         16,
    radiusFull:       999,
    density:          'normal',
    shadow:           '0 4px 30px rgba(139,92,246,0.15)',
    glowPrimary:      '0 0 25px rgba(139,92,246,0.3)',
    navPattern:       'sidebar-icon',
    success:          '#10B981',
    warning:          '#F59E0B',
    danger:           '#EF4444',
  },
}

export function generateDesignProfile(category: StartupCategory): DesignProfile {
  const style = CATEGORY_TO_STYLE[category]
  return PROFILES[style]
}
